server {
    listen 80;
    server_name _;
    absolute_redirect off;
    server_name_in_redirect off;
    port_in_redirect on;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location = /redirect.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        try_files $uri =404;
    }

    location = / {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        try_files /index.html =404;
    }

    location = /docs/overview {
        return 301 /docs/overview/;
    }

    location = /zh-CN/docs/overview {
        return 301 /zh-CN/docs/overview/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
