[system]
language = "${env:MEYO_LANG:-zh}"
api_keys = []
encrypt_key = "${env:MEYO_ENCRYPT_KEY:-meyo_local_encrypt_key}"

[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "postgresql"
host = "${env:MEYO_PG_HOST:-127.0.0.1}"
port = "${env:MEYO_PG_PORT:-14001}"
database = "${env:MEYO_PG_DATABASE:-meyo}"
user = "${env:MEYO_PG_USER:-meyo}"
password = "${env:MEYO_PG_PASSWORD:-meyo_local_20260321}"
schema = "public"

[service.model.worker]
host = "127.0.0.1"

[service.model.api]
controller_addr = "http://127.0.0.1:5670"

[rag.storage]
[rag.storage.vector]
type = "milvus"
uri = "${env:MEYO_MILVUS_HOST:-127.0.0.1}"
port = "${env:MEYO_MILVUS_PORT:-14009}"
alias = "default"

[models]
[[models.llms]]
name = "${env:MEYO_LANGUAGE_MODEL_NAME:-Pro/zai-org/GLM-5.1}"
provider = "proxy/siliconflow"
api_key = "${env:SILICONFLOW_API_KEY}"

[[models.embeddings]]
name = "${env:MEYO_EMBEDDING_MODEL_NAME:-Qwen/Qwen3-Embedding-8B}"
provider = "proxy/siliconflow"
backend = "${env:MEYO_EMBEDDING_MODEL_NAME:-Qwen/Qwen3-Embedding-8B}"
api_key = "${env:SILICONFLOW_API_KEY}"

[[models.rerankers]]
name = "${env:MEYO_RERANKER_MODEL_NAME:-BAAI/bge-reranker-v2-m3}"
provider = "proxy/siliconflow"
api_key = "${env:SILICONFLOW_API_KEY}"
