[system]
# 从环境变量读取默认语言，未设置时使用默认值。
language = "${env:MEYO_LANG:-zh}"
api_keys = []
encrypt_key = "${env:MEYO_ENCRYPT_KEY:-your_secret_key}"

# 服务配置
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "sqlite"
path = "pilot/meta_data/meyo.db"

[rag.storage]
[rag.storage.vector]
type = "chroma"
persist_path = "pilot/data"

# 模型配置
[models]
[[models.llms]]
name = "DeepSeek-R1-Distill-Qwen-1.5B"
provider = "llama.cpp"
# 未配置时会从 Hugging Face 模型仓库下载。
# 如需使用本地模型路径，取消下面配置的注释。
# https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF
# path = "本地模型路径"
path = "models/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf"


[[models.embeddings]]
name = "BAAI/bge-large-zh-v1.5"
provider = "hf"
# 未配置时会从 Hugging Face 模型仓库下载。
# 如需使用本地模型路径，取消下面配置的注释。
# path = "本地模型路径"
path = "models/BAAI/bge-large-zh-v1.5"

